extension.neon, src/bitExpert/PHPStan/Magento/Reflection/SessionManagerMagicMethodParameterReflection.php, src/bitExpert/PHPStan/Magento/Reflection/SessionManagerMagicMethodReflection.php, src/bitExpert/PHPStan/Magento/Reflection/SessionManagerMagicMethodReflectionExtension.php
Give PHPStan the possibility to understand the magic method calls made on SessionManager (aka get, set, unset or has).
=> Add reflection logic for SessionManager::call

composer.json, composer.lock
=> Support phpstan's extension-installer

src/bitExpert/PHPStan/Magento/Autoload/ProxyAutoloader.php
Fixes #11 by adding logic to generate interface methods in proxy classes as well.
=> Extend Proxy Autoloader to deal with interfaces

README.md
=> Added known issue for when using phpstan shim

composer.json, composer.lock, src/bitExpert/PHPStan/Magento/Reflection/AbstractMagicMethodReflectionExtension.php, src/bitExpert/PHPStan/Magento/Reflection/MagicMethodParameterReflection.php, src/bitExpert/PHPStan/Magento/Reflection/MagicMethodReflection.php
=> Make package compatible with PHPStan 0.12.18

autoload.php, src/bitExpert/PHPStan/Magento/Autoload/TestFrameworkAutoloader.php
=> Add autoloader for Magento\TestFramework classes

src/bitExpert/PHPStan/Magento/Autoload/ProxyAutoloader.php
Fix for proxy generation, as stated in #46 
Thanks for your work!
=> Fix proxy generation

phpstan.neon, src/bitExpert/PHPStan/Magento/Autoload/FactoryAutoloader.php
..and phpstan/phpstan-strict-rules
=> PHPStan extensions run on max :)

.allowed-licenses, composer.json, composer.lock
Upgrading Composer dependencies to their latest versions (except PHPstan because we want to support older Magento versions).
=> Composer dependency upgrade

.github/workflows/ci.yml, README.md, composer.json, composer.lock, phpstan.neon, tests/bitExpert/PHPStan/Magento/Rules/GetCollectionMockMethodNeedsCollectionSubclassRuleUnitTest.php, tests/bitExpert/PHPStan/Magento/Rules/Helper/dynamic_method_returntype_extension.neon, tests/bitExpert/PHPStan/Magento/Type/ObjectManagerDynamicReturnTypeExtensionUnitTest.php, tests/bitExpert/PHPStan/Magento/Type/TestFrameworkObjectManagerDynamicReturnTypeExtensionUnitTest.php
Upgrade PHPStan minimum requirement to version 1.1. Fixes #152
=> Drop support for PHPStan 0.12.x

README.md, docs/features.md
Fixes #166. Improved the docs to make the installation process a bit clearer.
=> Improve docs

composer.json, composer.lock
Make the extension compatible and installable with PHPStan 1.2.
=> Upgrade to PHPStan 1.2, drop support for PHPStan 1.1

bin/ci_markdown_neon_lint, bin/ci_neon_lint
=> Check if classes referenced in neon config exist

composer.json, extension.neon, phpstan.neon, src/bitExpert/PHPStan/Magento/Autoload/ExtensionAutoloader.php, tests/bitExpert/PHPStan/Magento/Autoload/ExtensionAutoloaderUnitTest.php, tests/bitExpert/PHPStan/Magento/Autoload/HelperExtension.php
Fixes #198. Besides the "ExtensionInterface," the "Extension" class is generated.
=> Add autoloader for extension classes

README.md
=> add documenation for composer plugins

src/bitExpert/PHPStan/Magento/Autoload/FactoryAutoloader.php, tests/bitExpert/PHPStan/Magento/Autoload/FactoryAutoloaderUnitTest.php, tests/bitExpert/PHPStan/Magento/Autoload/FactoryThingFactory.php
=> Fix factory generation for "FactoryThing" classes

src/bitExpert/PHPStan/Magento/Autoload/DataProvider/ExtensionAttributeDataProvider.php, src/bitExpert/PHPStan/Magento/Autoload/ExtensionAutoloader.php, src/bitExpert/PHPStan/Magento/Autoload/ExtensionInterfaceAutoloader.php
=> Allow arrays in extension attributes

extension.neon, src/bitExpert/PHPStan/Magento/Autoload/TestFrameworkAutoloader.php, tests/bitExpert/PHPStan/Magento/Autoload/RegistrationUnitTest.php
=> Use Magento root for TestFrameworkAutoloader

src/bitExpert/PHPStan/Magento/Autoload/TestFrameworkAutoloader.php
Fixes #271. Remove type hint for PHP 7.2 compatibility.
=> Make code compatible with PHP 7.2

src/bitExpert/PHPStan/Magento/Autoload/ExtensionAutoloader.php, src/bitExpert/PHPStan/Magento/Autoload/ExtensionInterfaceAutoloader.php
=> Don't use ?array type hint in ext attributes

docs/features.md, extension.neon, phpstan.neon, src/bitExpert/PHPStan/Magento/Rules/SetTemplateDisallowedForBlockRule.php, tests/bitExpert/PHPStan/Magento/Rules/Helper/SampleBlock.php, tests/bitExpert/PHPStan/Magento/Rules/Helper/block_settemplate.php, tests/bitExpert/PHPStan/Magento/Rules/SetTemplateDisallowedForBlockRuleUnitTest.php
=> Add rule "Disallow setTemplate() in Block classes"

extension.neon
=> Fix problem with parametersSchema
