- src/Magento/Framework/App/RequestInterface.php
- src/Magento/Store/Api/Data/StoreInterface.php
- src/bitExpert/PHPStan/Magento/Autoload/Autoloader.php
- src/bitExpert/PHPStan/Magento/Autoload/MockAutoloader.php
The MockAutoloader can be used to "overwrite" existing Magento classes and replace them with local copies. This is needed as not all interfaces expose all methods that can be called. Until this is fixed in Magento the mechanism can make sure that PHPStan knows about those methods and does not complain.
> Introduce MockAutoloader

- src/bitExpert/PHPStan/Magento/Reflection/Framework/DataObjectMagicMethodReflectionExtension.php
Apparently $classReflection->isSubclassOf() does not take the whole inheritance chain into account, it will just check if the direct parent class is DataObject.
> Optimize detection of DataObject parent class

- README.md
- autoload.php
Since the phar version makes use of dynamic namespaces the hack in registration.php to overload spl_autoload_register() and spl_autoload_unregister() does not work anymore. This PR adds a default autoload.php file which can be included via PHPStan's config file.
> Provide default autoload.php for PHPStan phar

- build.xml
- src/Magento/Framework/DB/Select.php
Magento\Framework\DB\Select::where() expects string|null for value but also array|int are allowed.
> Add Select mock file to fix where() doc block

- src/bitExpert/PHPStan/Magento/Reflection/Framework/DataObjectMagicMethodReflectionExtension.php
Commit https://github.com/bitExpert/phpstan-magento/commit/a72458ce869ee00ae011e30fb4c5a215cd9ee1c1 broke the fix added in https://github.com/bitExpert/phpstan-magento/pull/12
Without this fix, I'm getting the following error when executing phpstan:
```
Call to an undefined method Magento\Framework\DataObject::setSomeProperty()
```
> Fix Magic Method call on a DataObject instance

- src/bitExpert/PHPStan/Magento/Reflection/AbstractMagicMethodReflectionExtension.php
- src/bitExpert/PHPStan/Magento/Reflection/Framework/DataObjectMagicMethodReflectionExtension.php
- tests/bitExpert/PHPStan/Magento/Reflection/Framework/DataObjectMagicMethodReflectionExtensionUnitTest.php
Instead of accepting and returning mixed types, the extension now accepts and returns types based on the magic method documentation in the DataObject class.
> Make DataObject extension stricter

- .travis.yml
- README.md
- auth.json.enc
- composer.json
- composer.lock
- extension.neon
- phpstan.neon
- src/bitExpert/PHPStan/Magento/Rules/AbstractModelRetrieveCollectionViaFactoryRule.php
- src/bitExpert/PHPStan/Magento/Rules/AbstractModelUseServiceContractRule.php
- tests/bitExpert/PHPStan/Magento/Rules/AbstractModelRetrieveCollectionViaFactoryRuleUnitTest.php
- tests/bitExpert/PHPStan/Magento/Rules/AbstractModelUseServiceContractRuleUnitTest.php
- tests/bitExpert/PHPStan/Magento/Rules/Helper/SampleModel.php
- tests/bitExpert/PHPStan/Magento/Rules/Helper/collection.php
- tests/bitExpert/PHPStan/Magento/Rules/Helper/service_contract.php
Access to save(), load(), delete() and getCollection() is deprecated.
> Add deprecation rules for AbstractModel classes

- composer.json
- composer.lock
As described in #42 if I got you right. :)
> Use same constraint as latest Magento release

- README.md
- composer.json
- composer.lock
Fixes #42, replaces #43
My Engrish might not be super good, so if the warning should be phrased differently, let me know! 🙂 
Only took me 5 attempts with the captain hooks configuration for writing a valid commit message 😆
> Removes upper version constraint of phpstan

- src/bitExpert/PHPStan/Magento/Reflection/AbstractMagicMethodReflectionExtension.php
- src/bitExpert/PHPStan/Magento/Reflection/Framework/Session/SessionManagerMagicMethodReflectionExtension.php
- tests/bitExpert/PHPStan/Magento/Reflection/Framework/DataObjectMagicMethodReflectionExtensionUnitTest.php
- tests/bitExpert/PHPStan/Magento/Reflection/Framework/Session/SessionManagerMagicMethodReflectionExtensionUnitTest.php
The logic in AbstractMagicMethodReflectionExtension needed to be extended to deal with both `getData("Var")` and `getVar()`  invocations. Fixes #51. 
Also added a distinction between `DataObject::getData()` and `Session\Storage::getData()`.
> Fix params for DataObject get & set

- composer.json
- composer.lock
- src/bitExpert/PHPStan/Magento/Autoload/Cache/FileCacheStorage.php
- src/bitExpert/PHPStan/Magento/Autoload/FactoryAutoloader.php
- src/bitExpert/PHPStan/Magento/Autoload/ProxyAutoloader.php
- src/bitExpert/PHPStan/Magento/Reflection/Framework/DataObjectMagicMethodReflectionExtension.php
- src/bitExpert/PHPStan/Magento/Reflection/Framework/Session/SessionManagerMagicMethodReflectionExtension.php
- src/bitExpert/PHPStan/Magento/Reflection/MagicMethodReflection.php
- src/bitExpert/PHPStan/Magento/Rules/AbstractModelRetrieveCollectionViaFactoryRule.php
- src/bitExpert/PHPStan/Magento/Rules/AbstractModelUseServiceContractRule.php
- src/bitExpert/PHPStan/Magento/Rules/GetCollectionMockMethodNeedsCollectionSubclassRule.php
- tests/bitExpert/PHPStan/Magento/Type/TestFrameworkObjectManagerDynamicReturnTypeExtensionUnitTest.php
I can carry a sack of rocks 🗿🗿🗿 but this is mountain! ⛰️ 
From https://github.com/bitExpert/phpstan-magento/pull/64#issuecomment-777251168
> Add phpstan/phpstan-strict-rules

- .github/workflows/ci.yml
#67 broke CI, this PR fixes it: When downgrading phpstan to the version shipped with Magento 2.4.0, downgrade to the matching version of the strict rules package.
> Install matching lowest version of strict rules

- composer.json
- composer.lock
- src/bitExpert/PHPStan/Magento/Reflection/Framework/DataObjectMagicMethodReflectionExtension.php
- src/bitExpert/PHPStan/Magento/Reflection/Framework/Session/SessionManagerMagicMethodReflectionExtension.php
- src/bitExpert/PHPStan/Magento/Rules/GetCollectionMockMethodNeedsCollectionSubclassRule.php
- src/bitExpert/PHPStan/Magento/Type/TestFrameworkObjectManagerDynamicReturnTypeExtension.php
- tests/bitExpert/PHPStan/Magento/Reflection/Framework/DataObjectMagicMethodReflectionExtensionUnitTest.php
Fixes #113. Turned `magento/framework` into a dev dependency and define a conflict condition to make sure the minimum` magento/framework` requirements are met.
> Turn magento/framework into dev dependency

- src/bitExpert/PHPStan/Magento/Autoload/FactoryAutoloader.php
If we use Factory in the code for a class that does not have a namespace, phpstan will return an error.
For example: `use Zend_Db_Adapter_SqlsrvFactory`
In this case, the generated file has an empty namespace.
This pull request adds a condition that makes this case remain without a namespace.
**Before:**
**After:**
> Omit namespace for non-namespace Factory

- src/bitExpert/PHPStan/Magento/Autoload/ProxyAutoloader.php
Apply the logic of #132 also for the proxy class autoloader: Omit the namespace in the generated file if the source class does not contain a namespace element.
> Omit namespace for non-namespace Proxy

- autoload.php
- extension.neon
- phpstan.neon
- src/bitExpert/PHPStan/Magento/Autoload/Autoloader.php
- src/bitExpert/PHPStan/Magento/Autoload/FactoryAutoloader.php
- src/bitExpert/PHPStan/Magento/Autoload/MockAutoloader.php
- src/bitExpert/PHPStan/Magento/Autoload/ProxyAutoloader.php
- src/bitExpert/PHPStan/Magento/Autoload/TestFrameworkAutoloader.php
- tests/bitExpert/PHPStan/Magento/Autoload/RegistrationUnitTest.php
> Determine tmpDir path relative to config file when appropriate

- autoload.php
Optimization for #163: Replaced the echo/die logic by throwing an exception to let PHPStan terminate cleanly.
> Throw exception in autoloader

- composer.json
- composer.lock
Due to the changes in #163 we don't need the nette/neon dependency anymore, since we don't have to re-parse the PHPStan configuration file. The autoloader gets the DI container injected which we then can use to pull all dependencies we need from.
> Remove nette/neon dependency

- .github/workflows/ci.yml
- bin/ci_markdown_neon_lint
- bin/ci_neon_lint
- composer.json
- composer.lock
- docs/features.md
To make sure the neon configuration files like `extension.neon` or `phpstan.neon` are valid, check those files in the CI pipeline.
Additionally, also check the neon configuration snippets in the Markdown files to make sure the syntax is correct.
> Lint neon files in CI pipeline

- composer.json
- composer.lock
- docs/features.md
- extension.neon
- phpstan.neon
- src/bitExpert/PHPStan/Magento/Autoload/DataProvider/ClassLoaderProvider.php
- src/bitExpert/PHPStan/Magento/Autoload/DataProvider/ExtensionAttributeDataProvider.php
- src/bitExpert/PHPStan/Magento/Autoload/ExtensionInterfaceAutoloader.php
- tests/bitExpert/PHPStan/Magento/Autoload/DataProvider/ClassLoaderProviderUnitTest.php
- tests/bitExpert/PHPStan/Magento/Autoload/DataProvider/ExtensionAttributeDataProviderUnitTest.php
- tests/bitExpert/PHPStan/Magento/Autoload/ExtensionInterfaceAutoloaderUnitTest.php
- tests/bitExpert/PHPStan/Magento/Autoload/HelperExtensionInterface.php
- tests/bitExpert/PHPStan/Magento/Autoload/RegistrationUnitTest.php
Fixes #174
In contrast to my plan outlined in #174, I took a different route as I realized that it can be problematic to depend on Magento framework classes (loading and analyzing framework classes at the same time). Additionally, it was not possible to install PHPStan and this extension in a different directory as then the Composer autoloader would not work for the project-specific classes (e.g. for the class_exists, interface_exists, and trait_exists checks).
What happens now is that all `extension_attributes.xml` found in `etc` directories are loaded recursively and evaluated regardless of whether the module is active or not. By default, the current working directory (the directory you placed your `phpstan.neon` file in) will be used as a starting point. If you need to change that, you …
> Rework extension attribute handling for standalone modules

- composer.json
Restrict the PHPStan version to 1.6 max due to compatibility problems with PHPStan 1.7 (see #243).
> Do not yet install PHPStan 1.7

- composer.json
- src/bitExpert/PHPStan/Magento/Autoload/DataProvider/ExtensionAttributeDataProvider.php
- src/bitExpert/PHPStan/Magento/Autoload/ExtensionInterfaceAutoloader.php
- tests/bitExpert/PHPStan/Magento/Autoload/ExtensionInterfaceAutoloaderUnitTest.php
Things done:
- Allow higher versions of `laminas/laminas-code` to be installed which brings in PHP 8.2 / Magento 2.4.6 support.
- Also replaced PHP 8.2 deprecated syntax.
- Also added test for exception message (wanted to make sure nothing broke by my change)
I hope you don't mind me switching to the `sprintf` function, I like that better than concatenating strings, it looks a bit more readable this way in my opinion.
Fixes #282
> Adds PHP 8.2 / Magento 2.4.6 support

- docs/features.md
- extension.neon
- src/bitExpert/PHPStan/Magento/Rules/ResourceModelsShouldBeUsedDirectlyRule.php
- tests/bitExpert/PHPStan/Magento/Rules/Helper/resource_model.php
- tests/bitExpert/PHPStan/Magento/Rules/ResourceModelsShouldBeUsedDirectlyRuleUnitTest.php
> Add rule "resource models should be used directly"

- bin/ci_neon_lint
Fixes #303 
Not only check if classes that have been defined in the extension.neon file exist but also if the `parameters` section matches the schema definition in `parametersSchema`.
> Extend Neon validation logic for CI

- composer.json
This ensures this tool is compatible to run alongside newer versions of other codestyle tools.
> Add support for symfony/finder 7+

- composer.json
- src/bitExpert/PHPStan/Magento/Autoload/DataProvider/ClassLoaderProvider.php
- src/bitExpert/PHPStan/Magento/Autoload/FactoryAutoloader.php
- src/bitExpert/PHPStan/Magento/Autoload/ProxyAutoloader.php
- src/bitExpert/PHPStan/Magento/Reflection/MagicMethodReflection.php
- src/bitExpert/PHPStan/Magento/Rules/AbstractModelRetrieveCollectionViaFactoryRule.php
- src/bitExpert/PHPStan/Magento/Rules/AbstractModelUseServiceContractRule.php
- src/bitExpert/PHPStan/Magento/Rules/GetCollectionMockMethodNeedsCollectionSubclassRule.php
- src/bitExpert/PHPStan/Magento/Rules/ResourceModelsShouldBeUsedDirectlyRule.php
- src/bitExpert/PHPStan/Magento/Rules/SetTemplateDisallowedForBlockRule.php
- src/bitExpert/PHPStan/Magento/Type/ObjectManagerDynamicReturnTypeExtension.php
- src/bitExpert/PHPStan/Magento/Type/TestFrameworkObjectManagerDynamicReturnTypeExtension.php
- tests/bitExpert/PHPStan/Magento/Autoload/RegistrationUnitTest.php
- tests/bitExpert/PHPStan/Magento/Reflection/Framework/DataObjectMagicMethodReflectionExtensionUnitTest.php
- tests/bitExpert/PHPStan/Magento/Reflection/Framework/Session/SessionManagerMagicMethodReflectionExtensionUnitTest.php
- tests/bitExpert/PHPStan/Magento/Reflection/MagicMethodReflectionUnitTest.php
- tests/bitExpert/PHPStan/Magento/Rules/AbstractModelRetrieveCollectionViaFactoryRuleUnitTest.php
- tests/bitExpert/PHPStan/Magento/Rules/AbstractModelUseServiceContractRuleUnitTest.php
- tests/bitExpert/PHPStan/Magento/Rules/GetCollectionMockMethodNeedsCollectionSubclassRuleUnitTest.php
- tests/bitExpert/PHPStan/Magento/Rules/ResourceModelsShouldBeUsedDirectlyRuleUnitTest.php
- tests/bitExpert/PHPStan/Magento/Rules/SetTemplateDisallowedForBlockRuleUnitTest.php
- tests/bitExpert/PHPStan/Magento/Type/TestFrameworkObjectManagerDynamicReturnTypeExtensionUnitTest.php
I went over https://github.com/phpstan/phpstan/blob/2.0.x/UPGRADING.md#upgrading-guide-for-extension-developers
More specifically these 2 guides, which can be seen in 2 individual commits in this PR:
- https://phpstan.org/blog/using-rule-error-builder
- https://phpstan.org/blog/why-is-instanceof-type-wrong-and-getting-deprecated
Even more in detail:
1. Using RuleErrorBuilder instead of returning strings:
- wrapped the previous string into a RuleError object
- introduced an identifier using the format `bitExpertMagento.{classname-without-Rule-suffix-and-lowercase-starting-letter}` ([the regex only allows letters and digits and dots, no dashes or underscores](https://github.com/phpstan/phpstan-src/blob/9c06f13887ef9977ffe2cab25b3ec71af246675c/src/Analyser/Error.php#L21))
- The guide …
> On the road to phpstan 2.0 compatibility

- src/bitExpert/PHPStan/Magento/Autoload/ProxyAutoloader.php
The following code was being generated when I had a proxyClass on Scope config.
This seems like the correct fix to me
> fix: error where scopeConfig proxy would get $scopeType = default
